# Generated by Django 4.2.2 on 2023-06-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lnkdn',
            new_name='address',
        ),
    ]
